# (This file is not use anymore by GenoM. Will probably disappear soon).
#
# Fichier généré automatiquement  Ne pas éditer manuellement !!!
#
# Makefile for protypes
#
# Copyright (C) 1996 LAAS/CNRS
#
# $Id$
#
include ../../../Init.make
include ../../../Init.make.host.$(MACHTYPE)-$(OSTYPE)
include ../../../Init.make.$(MACHTYPE)-$(OSTYPE)

CPPFLAGS +=  -I$(DIRUNIX) -I$(DIRGENOM) -DUNIX

PROTOS = \
	$module$MsgLibPrsProto.h \
	$module$PosterLibProto.h \
	$module$PosterShowLibProto.h \
	$module$PosterWriteLibProto.h \
	$module$PrintProto.h \
	$module$ScanProto.h \
	$module$ScopeLibProto.h \
	$module$InitProto.h \
$genTcl$	$module$TclProto.h \

PROTOS_STAMP = $(PROTOS:%.h=.%_stamp)

all: $(PROTOS_STAMP) $(PROTOS)

# Si stamps plus anciens que .c
.%Proto_stamp: %.c
	@echo prototype $<
	$(CEXTRACT) $(CPPFLAGS) -o tmp-$*.h $< 2>/dev/null
	move-if-change tmp-$*.h $*Proto.h 
	touch $@

# Si proto.h n'existe pas
%Proto.h:
	@echo create $@
	$(CEXTRACT) $(CPPFLAGS) -o $@ $*.c 2>/dev/null
	touch .$*Proto_stamp


.PRECIOUS: $(PROTOS)

