/*	$LAAS$ */

/* 
 * Copyright (c) 2003 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution and use  in source  and binary  forms,  with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice,  this list of  conditions and the following disclaimer in
 *      the  documentation  and/or  other   materials provided  with  the
 *      distribution.
 *
 * THIS  SOFTWARE IS PROVIDED BY  THE  COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND  ANY  EXPRESS OR IMPLIED  WARRANTIES,  INCLUDING,  BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR  PURPOSE ARE DISCLAIMED. IN  NO EVENT SHALL THE COPYRIGHT
 * HOLDERS OR      CONTRIBUTORS  BE LIABLE FOR   ANY    DIRECT, INDIRECT,
 * INCIDENTAL,  SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN  CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE   OF THIS SOFTWARE, EVEN   IF ADVISED OF   THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

/*
 * Automatically generated by GenoM : do not edit by hand
 * Read data from the posters produced by the module $module$
 */


#include <stdio.h>
#include <stdlib.h>
#ifdef VXWORKS
#include <vxWorks.h>
#else
#include "portLib.h"
#endif

#include "$module$PosterLib.h"
#include "$module$Print.h"
#include "$module$Endian.h"

#include "genom/h2endian.h"

/* Id. du poster de controle */
static POSTER_ID $module$CntrlPosterId=(POSTER_ID)NULL;
static H2_ENDIANNESS posterDataEndianness;

/*  prototypes de la bibliotheque printState */
extern char const * h2GetEvnStateString(int num);

/* ---------------- LE POSTER DE CONTROLE ------------------------------ */

/* ----------------------------------------------------------------------
 *
 *  $module$CntrlPosterRead - Lecture du poster de controle du module
 *
 */

POSTER_ID $module$CntrlPosterID () { return $module$CntrlPosterId; }

STATUS $module$CntrlPosterRead ($MODULE$_CNTRL_STR *$module$CntrlStrId)
{  
  if (!$module$CntrlPosterId)
    $module$CntrlPosterInit();
  if (posterRead ($module$CntrlPosterId, 0, (void *) $module$CntrlStrId, 
	      sizeof($MODULE$_CNTRL_STR)) != sizeof($MODULE$_CNTRL_STR))
    return ERROR; 
  return OK;
}

/* ---------------- LES POSTERS FONCTIONNELS ------------------------------ */

