/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern ESSAY_STR * essayInit ( int essayNum, char *module, int mboxsize, int abortRqstNum, int nbRqstType, char *rqstName[], ESSAY_RQST_DESC_STR *rqstDesc, int nbPosters, char *posterName[], ESSAY_POSTER_SHOW_FUNC_PTR posterShowFunc[] );
extern void essayEnd ( ESSAY_STR *eid );
extern void essayMain ( ESSAY_STR *eid );
extern BOOL essaySendAndRcvCntrlRqst ( ESSAY_STR *eid, int rqstNum, int acti, int sendRcvMode, GENOM_REPORTS_STRUCT *localFail );
extern BOOL essaySendAndOrRcvExecRqst ( ESSAY_STR *eid, int rqstNum, int acti, int sendRcvMode, GENOM_REPORTS_STRUCT *localFail );
extern BOOL essaySendAndGetInput ( ESSAY_STR *eid, int rqstGet, int acti, void *output );
extern BOOL essayPrintGetInputMenu ( ESSAY_STR *essayId, int nbItems, const char **menu, int rqstNum );

#else /* __STDC__ */

extern ESSAY_STR * essayInit (/* int essayNum, char *module, int mboxsize, int abortRqstNum, int nbRqstType, char *rqstName[], ESSAY_RQST_DESC_STR *rqstDesc, int nbPosters, char *posterName[], ESSAY_POSTER_SHOW_FUNC_PTR posterShowFunc[] */);
extern void essayEnd (/* ESSAY_STR *eid */);
extern void essayMain (/* ESSAY_STR *eid */);
extern BOOL essaySendAndRcvCntrlRqst (/* ESSAY_STR *eid, int rqstNum, int acti, int sendRcvMode, GENOM_REPORTS_STRUCT *localFail */);
extern BOOL essaySendAndOrRcvExecRqst (/* ESSAY_STR *eid, int rqstNum, int acti, int sendRcvMode, GENOM_REPORTS_STRUCT *localFail */);
extern BOOL essaySendAndGetInput (/* ESSAY_STR *eid, int rqstGet, int acti, void *output */);
extern BOOL essayPrintGetInputMenu (/* ESSAY_STR *essayId, int nbItems, const char **menu, int rqstNum */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
