/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern char const * h2getLocalMsgErrno ( GENOM_REPORTS_STRUCT *failuresMsg, int error );
extern void h2printLocalErrno ( GENOM_REPORTS_STRUCT *failuresMsg, int numErr );

#else /* __STDC__ */

extern char const * h2getLocalMsgErrno (/* GENOM_REPORTS_STRUCT *failuresMsg, int error */);
extern void h2printLocalErrno (/* GENOM_REPORTS_STRUCT *failuresMsg, int numErr */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
