/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Mar  3 18:26:52 2005
 */
#ifndef __CEXTRACT__
#if __STDC__

extern STATUS genomGiveSDIs ( void *sdic );
extern STATUS genomTakeSDIs ( void *sdic );

#else /* __STDC__ */

extern STATUS genomGiveSDIs (/* void *sdic */);
extern STATUS genomTakeSDIs (/* void *sdic */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
