/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern void endianswap_char ( char *thechar, int nDim, int *dims );
extern void endianswap_string ( char *thechar, int nDim, int *dims );
extern void endianswap_unsigned_char ( unsigned char *x, int nDim, int *dims );
extern void endianswap_double ( double *x, int nDim, int *dims );
extern void endianswap_longlong ( long long *thelonglong, int nDim, int *dims );
extern void endianswap_longlong_elt ( long long *thelonglong );
extern void endianswap_short_int ( short int *theshort, int nDim, int *dims );
extern void endianswap_short_int_elt ( short int *theshort );
extern void endianswap_unsigned_short_int ( unsigned short int *theshort, int nDim, int *dims );
extern void endianswap_unsigned_int ( unsigned int *theint, int nDim, int *dims );
extern void endianswap_int ( int *theint, int nDim, int *dims );
extern void endianswap_int_elt ( int *theint );
extern void endianswap_long_int ( long int *theint, int nDim, int *dims );
extern void endianswap_long_int_elt ( long int *theint );
extern void endianswap_unsigned_long_int ( unsigned long int *theint, int nDim, int *dims );
extern void endianswap_float ( float *thefloat, int nDim, int *dims );
extern void endianswap_buffer ( char *buf, unsigned char bufsize );

#else /* __STDC__ */

extern void endianswap_char (/* char *thechar, int nDim, int *dims */);
extern void endianswap_string (/* char *thechar, int nDim, int *dims */);
extern void endianswap_unsigned_char (/* unsigned char *x, int nDim, int *dims */);
extern void endianswap_double (/* double *x, int nDim, int *dims */);
extern void endianswap_longlong (/* long long *thelonglong, int nDim, int *dims */);
extern void endianswap_longlong_elt (/* long long *thelonglong */);
extern void endianswap_short_int (/* short int *theshort, int nDim, int *dims */);
extern void endianswap_short_int_elt (/* short int *theshort */);
extern void endianswap_unsigned_short_int (/* unsigned short int *theshort, int nDim, int *dims */);
extern void endianswap_unsigned_int (/* unsigned int *theint, int nDim, int *dims */);
extern void endianswap_int (/* int *theint, int nDim, int *dims */);
extern void endianswap_int_elt (/* int *theint */);
extern void endianswap_long_int (/* long int *theint, int nDim, int *dims */);
extern void endianswap_long_int_elt (/* long int *theint */);
extern void endianswap_unsigned_long_int (/* unsigned long int *theint, int nDim, int *dims */);
extern void endianswap_float (/* float *thefloat, int nDim, int *dims */);
extern void endianswap_buffer (/* char *buf, unsigned char bufsize */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
