/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern int get_sub_array_indexes ( FILE *out, FILE *in, int indent, int nDim, int *dims, int *start );
extern void print_addr ( FILE *out, void **x, int indent, int nDim, int *dims, FILE *in );
extern void print_char ( FILE *out, char *x, int indent, int nDim, int *dims, FILE *in );
extern void print_double ( FILE *out, double *x, int indent, int nDim, int *dims, FILE *in );
extern void print_float ( FILE *out, float *x, int indent, int nDim, int *dims, FILE *in );
extern void print_int ( FILE *out, int *x, int indent, int nDim, int *dims, FILE *in );
extern void print_long_int ( FILE *out, long int *x, int indent, int nDim, int *dims, FILE *in );
extern void print_short_int ( FILE *out, short int *x, int indent, int nDim, int *dims, FILE *in );
extern void print_string ( FILE *out, char *x, int indent, int nDim, int *dims, FILE *in );
extern void print_string_len ( FILE *out, char *x, int max_str_len, int indent, int nDim, int *dims, FILE *in );
extern void print_unsigned_char ( FILE *out, unsigned char *x, int indent, int nDim, int *dims, FILE *in );
extern void print_unsigned_int ( FILE *out, unsigned int *x, int indent, int nDim, int *dims, FILE *in );
extern void print_unsigned_long_int ( FILE *out, unsigned long *x, int indent, int nDim, int *dims, FILE *in );
extern void print_unsigned_short_int ( FILE *out, unsigned short *x, int indent, int nDim, int *dims, FILE *in );

#else /* __STDC__ */

extern int get_sub_array_indexes (/* FILE *out, FILE *in, int indent, int nDim, int *dims, int *start */);
extern void print_addr (/* FILE *out, void **x, int indent, int nDim, int *dims, FILE *in */);
extern void print_char (/* FILE *out, char *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_double (/* FILE *out, double *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_float (/* FILE *out, float *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_int (/* FILE *out, int *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_long_int (/* FILE *out, long int *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_short_int (/* FILE *out, short int *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_string (/* FILE *out, char *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_string_len (/* FILE *out, char *x, int max_str_len, int indent, int nDim, int *dims, FILE *in */);
extern void print_unsigned_char (/* FILE *out, unsigned char *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_unsigned_int (/* FILE *out, unsigned int *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_unsigned_long_int (/* FILE *out, unsigned long *x, int indent, int nDim, int *dims, FILE *in */);
extern void print_unsigned_short_int (/* FILE *out, unsigned short *x, int indent, int nDim, int *dims, FILE *in */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
