/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern TEST_STR * testInit ( int testNum, char *module, int mboxsize, int abortRqstNum, int nbRqstType, char *rqstName[], TEST_RQST_DESC_STR *rqstDesc, int nbPosters, char *posterName[], TEST_POSTER_SHOW_FUNC_PTR posterShowFunc[] );
extern void testEnd ( TEST_STR *eid );
extern void testMain ( TEST_STR *eid );
extern BOOL testSendAndRcvCntrlRqst ( TEST_STR *eid, int rqstNum, int acti, int sendRcvMode );
extern BOOL testSendAndOrRcvExecRqst ( TEST_STR *eid, int rqstNum, int acti, int sendRcvMode );
extern BOOL testSendAndGetInput ( TEST_STR *eid, int rqstGet, int acti, void *output );
extern BOOL testPrintGetInputMenu ( TEST_STR *testId, int nbItems, const char **menu, int rqstNum );

#else /* __STDC__ */

extern TEST_STR * testInit (/* int testNum, char *module, int mboxsize, int abortRqstNum, int nbRqstType, char *rqstName[], TEST_RQST_DESC_STR *rqstDesc, int nbPosters, char *posterName[], TEST_POSTER_SHOW_FUNC_PTR posterShowFunc[] */);
extern void testEnd (/* TEST_STR *eid */);
extern void testMain (/* TEST_STR *eid */);
extern BOOL testSendAndRcvCntrlRqst (/* TEST_STR *eid, int rqstNum, int acti, int sendRcvMode */);
extern BOOL testSendAndOrRcvExecRqst (/* TEST_STR *eid, int rqstNum, int acti, int sendRcvMode */);
extern BOOL testSendAndGetInput (/* TEST_STR *eid, int rqstGet, int acti, void *output */);
extern BOOL testPrintGetInputMenu (/* TEST_STR *testId, int nbItems, const char **menu, int rqstNum */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
