#	$LAAS$

#
# Copyright (c) 1993-2003 LAAS/CNRS
# All rights reserved.
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice, this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice,  this list of  conditions and  the following disclaimer in
#      the  documentation   and/or  other  materials   provided with  the
#      distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE  AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY  EXPRESS OR IMPLIED WARRANTIES, INCLUDING,  BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES   OF MERCHANTABILITY AND  FITNESS  FOR  A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO  EVENT SHALL THE AUTHOR OR  CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT,  INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING,  BUT  NOT LIMITED TO, PROCUREMENT  OF
# SUBSTITUTE  GOODS OR SERVICES;  LOSS   OF  USE,  DATA, OR PROFITS;   OR
# BUSINESS  INTERRUPTION) HOWEVER CAUSED AND  ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# 
# Compilation du module $module$ pour VxWorks
# 

# Au cas ou $MODULE$ n'est pas declare dans Init.make:
$MODULE$ = ..

include ../../../Init.make
include ../../../Init.make.$(TARGET)

RACK=h2

#------------------------------------------------------------------------
#   LISTE DES FICHIERS A COMPILER 
#   (vous pouvez modifier les trois definitions suivantes)
#------------------------------------------------------------------------

CPPFLAGS += $serversDir$ -I$(DIRHC) -I$(DIRSC) -I$(DIRTIM) \
	-I$(DIRCOM) -I$(DIRM) -I$(DIRHL) -I$(DIRGENOM) \
	-I$(DIRERR) -I$($MODULE$) -I$($MODULE$)/auto \
	-DRACK=$(RACK) $genomDefines$

SRCS = \
	$module$CntrlTaskCodels.c \
$listExecTaskFunc_c$

#-- Autres bibliotheques (compilees par ailleurs)
LIBS = 


#------------------------------------------------------------------------
#   REGLES DE COMPILATION ET D'EDITION DE LIENS
#------------------------------------------------------------------------

# Definitions
MODULE   = $(TARGET)/$module$.o
AUTO_OBJ = ../auto/$(TARGET)/$module$Module.o
POSTER_WRITE_LIB = ../auto/$(TARGET)/$module$PosterWriteLib.o
OBJS     = $(SRCS:%.c=$(TARGET)/%.o)

# Action par defaut: production du module
all:	$(MODULE)

# Edition de liens
$(MODULE): $(OBJS) $(AUTO_OBJ) $(POSTER_WRITE_LIB) $(LIBS)
	$(LD) -r -o $(MODULE) $(OBJS) $(AUTO_OBJ) $(POSTER_WRITE_LIB) $(LIBS)

# Regles standard 
$(TARGET)/%.o:	%.c
	$(CC) -c  -o $@ $(CPPFLAGS) $(CFLAGS) $<

# Nettoyage
clean:
	\rm -r $(TARGET)/*

# Dependances
MKDEPFLAGS = -sROOTH2=$(ROOTH2) -k 
depend $(TARGET)/DEPENDANCES.vxworks:: $(SRCS)
	@mkdir -p $(TARGET)
	$(MKDEP) $(MKDEPFLAGS) -i$(DIRVXH) -c$(CC) -o$(TARGET)/DEPENDANCES.vxworks -d$(TARGET) $(CPPFLAGS) $?

include $(TARGET)/DEPENDANCES.vxworks


