#	$LAAS$

#
# Copyright (c) 1996-2003 LAAS/CNRS
# All rights reserved.
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice, this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice,  this list of  conditions and  the following disclaimer in
#      the  documentation   and/or  other  materials   provided with  the
#      distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE  AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY  EXPRESS OR IMPLIED WARRANTIES, INCLUDING,  BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES   OF MERCHANTABILITY AND  FITNESS  FOR  A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO  EVENT SHALL THE AUTHOR OR  CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT,  INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING,  BUT  NOT LIMITED TO, PROCUREMENT  OF
# SUBSTITUTE  GOODS OR SERVICES;  LOSS   OF  USE,  DATA, OR PROFITS;   OR
# BUSINESS  INTERRUPTION) HOWEVER CAUSED AND  ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Fichier généré automatiquement
# Ne pas éditer manuellement !!!
include ../../../../Init.make

CPPFLAGS += $serversDir$ -I.. -I$(DIRUNIX) -I$(DIRHC) -I$(DIRGENOM) \
	-I$(DIRERR) -I$(DIRHL) \
	-I$(ROOTPROPICE)/include -I$(ROOTPROPICE)/contrib/include  \
	$genomDefines$

PROTOS = \
	$module$DecodePropiceProto.h \
	$module$EncodePropiceProto.h \
	$module$RequestsPropiceProto.h

PROTOS_STAMP = $(PROTOS:%.h=.%_stamp)

all: $(PROTOS_STAMP) $(PROTOS)

# Si stamps plus anciens que .c
.%Proto_stamp: %.c
	@echo prototype $<
	@$(CEXTRACT) $(CPPFLAGS) -o tmp-$*.h $< 2>/dev/null
	@move-if-change tmp-$*.h $*Proto.h 
	@touch $@

# Si proto.h n'existe pas
%Proto.h:
	@echo create $@
	@$(CEXTRACT) $(CPPFLAGS) -o $@ $*.c 2>/dev/null
	@touch .$*Proto_stamp


.PRECIOUS: $(PROTOS)

