#! /bin/sh
if test -f Makefile; then
    make distclean
fi
rm -fR server autom4te.cache .genom
rm -f \
    configure \
    configure.ac \
    aclocal.m4 \
    autogen

rm -f \
    autoconf/acinclude.m4  \
    autoconf/config.guess   \
    autoconf/config.posix.mk   \
    autoconf/config.sub           \
    autoconf/configure.ac.begin   \
    autoconf/install-sh   \
    autoconf/mkinstalldirs \
    autoconf/codels.mk      \
    autoconf/config.mk.in   \
    autoconf/config.rtai.mk    \
    autoconf/configure.ac.begin   \
    autoconf/libtool.m4   \
    autoconf/ltmain.sh   \
    autoconf/robots.m4

