#!/usr/bin/env perl
#
# Kill MY Genom modules under Unix
#
# Sara Fleury - Avril 2001
#
# $Id$
#----------------------------------------------------------------------
#

use warnings;

$killmodule =  "killmodule";

# Get a list of files corresponding to running modules
@list_files=`ls $ENV{'HOME'}/.*.pid-*`;

# walk the list
foreach $file (@list_files) {
  $_ = $file;

  # extract the module name
  if (/.(\w*).pid/) {
    $module = $1;
    
    # call killmodule
    printf "killmodule $module\n";
    `$killmodule $module`;
  }

  # module name not found ?!
  else {
    printf "Cannot get module name of $file\n";
  }
}

# done
exit 0;
